apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktp-frontend
  namespace: ktp
  labels:
   app: ktp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktp-frontend
  template:
    metadata:
      labels:
        app: ktp-frontend
    spec:
      containers:
      - name: ktp-frontend-container
        image: tonisnakes/privates:ktp-frontend-arm
        imagePullPolicy: Always
        env:
          - name: BASE_URL
            value: "http://ktp-backend-service.ktp:80"
        ports:
        - containerPort: 3000
          protocol: TCP
      imagePullSecrets:
      - name: docker-login
---
apiVersion: v1
kind: Service
metadata:
  name: ktp-frontend-service
  namespace: ktp
spec:
  selector:
    app: ktp-frontend
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-ktp-frontend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  namespace: ktp
spec:
  tls:
  - hosts:
    - ktp-frontend.tonisworkshop.com
    secretName: ktp-frontend-tls
  rules:
  - host: ktp-frontend.tonisworkshop.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ktp-frontend-service
            port:
              number: 80
